/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gastos.java
 *
 * Created on 12-dic-2012, 21:33:49
 */
package movimiento;

import Metodos.abm;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import gourmet.conexionBD;

/**
 *
 * @author User
 */
public class gastos extends javax.swing.JDialog {
        
    conexionBD cn;
    private abm abm;
    private boolean v_control;
    private boolean vacio;
    private ResultSet rs;
    private ResultSet rst;
    /** Creates new form gastos */
    public gastos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        abm=new abm();
        cn= new conexionBD();
        
        obtenerfecha();
        
        idfactura();
    }
void obtenerfecha(){
        Date fecha = new Date();
        SimpleDateFormat fe = new SimpleDateFormat("yyyy/MM/dd");
        this.fecha.setText(fe.format(fecha));   
    }
    public  boolean validardatos(){
   vacio=false;
   if(txtCosto.getText().isEmpty()){
       vacio=true;
        }
   if(txtConcepto.getText().isEmpty()){
       vacio=true;
        }
   return vacio;
}
    public void idfactura(){
        try {
            rs = abm.nuevo("idgastos","gastos");
            try {
                rs.first();
            } catch (SQLException ex) {
                Logger.getLogger(gastos.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtIdgastos.setText(String.valueOf(rs.getInt("codigo")+1));
        } catch (SQLException ex) {
            Logger.getLogger(gastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void limpiar(){
       txtCosto.setText("");
       txtConcepto.setText(""); 
    }
    
    void montogastos() {
        try {
            Statement consulta = (Statement) conexionBD.ConectarBD().createStatement();
                   rst = consulta.executeQuery("select sum(monto) as monto from gastos");
                   rst.first();
                   String gastos= rst.getString("monto");                   
                   
                 //  txtGastos.setText((gastos));
        } catch (SQLException ex) {
        }
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        txtIdgastos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 3, 18));
        jLabel1.setText("GASTOS VARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 23, 162, -1));

        jLabel2.setText("Concepto de Insumo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));
        getContentPane().add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 70));

        jLabel3.setText("Costo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, -1, 20));

        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, -1));

        txtIdgastos.setEnabled(false);
        getContentPane().add(txtIdgastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 238, 310, 10));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        fecha.setEnabled(false);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
    this.dispose();
    montogastos() ;
}//GEN-LAST:event_btnCancelarActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
    vacio=validardatos();
    if(vacio==true){
            JOptionPane.showMessageDialog(null,"Completar los datos marcados en aterisco");
        }
    else{
        int idempleado = abm.idUsuario;
    
     v_control=abm.insertar("gastos",txtIdgastos.getText()+","+txtCosto.getText()+",'"+txtConcepto.getText()+"','"+fecha.getText()+"',"+idempleado);
      if (v_control==true){
             JOptionPane.showMessageDialog(null,"Se ha guardado los datos");              
           }                                   
    }
    idfactura();
    limpiar();
    montogastos() ;
    this.dispose();
}//GEN-LAST:event_btnGuardarActionPerformed

private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
// TODO add your handling code here:
    char caracter=evt.getKeyChar();
        if((caracter<'0'||(caracter>'9'))&&(caracter!='\b')){
            evt.consume();
        }
}//GEN-LAST:event_txtCostoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                gastos dialog = new gastos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtIdgastos;
    // End of variables declaration//GEN-END:variables
}
