/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RestaurarBD.java
 *
 * Created on 01-ene-2013, 22:16:52
 */
package Vista;

import Controlador.MySQL;
import Controlador.Seleccion;
import gourmet.Principal;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tottus
 */
public class RestaurarBD extends javax.swing.JDialog {

    String user = "root";
    String password = "12345";
    String bd = "gourtmet";
    String path = "";
    String backup = "mysqldump --user=" + user + " --password=" + password + " -v " + bd + " > " + path;
    Principal p;
    MySQL mysql;
    

    public RestaurarBD(Principal parent, boolean modal) {
        super(parent, modal);
        p = parent;
        initComponents();
        this.setLocationRelativeTo(p);
        
        btnrestaurar.setVisible(false);
        btnexaminar.setVisible(false);
    }

    
    void restaurar(String pass, String us, String bd){
        int resp;
        String direccion_usuario = System.getProperty("user.dir");
        JFileChooser buscar_archivo = new JFileChooser(direccion_usuario);
        resp =buscar_archivo.showSaveDialog(this);
        if (resp==JFileChooser.APPROVE_OPTION){
            txtruta.setText(buscar_archivo.getSelectedFile().toString());
            try{
                String archivo = txtruta.getText();
                Process p= Runtime.getRuntime().exec("C:\\Program Files\\MySQL\\MySQL Workbench 6.3 CE\\mysql -u "+us+" -p"+pass+" "+bd+"");
               // new HiloLector(p.getErrorStream()).start();
                OutputStream os = p.getOutputStream();
                FileInputStream fis = new FileInputStream(archivo);
                
                byte[] buffer = new byte[1000];
                
                int leido =fis.read(buffer);
                
                while (leido >0){
                    os.write(buffer, 0, leido);
                    leido = fis.read(buffer);
                }
                os.flush();
                os.close();
                fis.close();
                JOptionPane.showMessageDialog(null,"Archivo restaurado de \n"+archivo," Proceso Finalizado",JOptionPane.INFORMATION_MESSAGE);
                txtruta.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error no se restauro por: "+e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrestaurar = new javax.swing.JButton();
        btnexaminar = new javax.swing.JButton();
        txtruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurar Base de Datos");
        setResizable(false);

        btnrestaurar.setText("Restaurar");
        btnrestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurarActionPerformed(evt);
            }
        });

        btnexaminar.setText("Examinar");
        btnexaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexaminarActionPerformed(evt);
            }
        });

        txtruta.setEditable(false);

        jLabel1.setText("Ruta :");

        jButton1.setText("Buscar y Restaurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnrestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrestaurar)
                    .addComponent(btnexaminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexaminarActionPerformed
        Seleccion o = new Seleccion();
        File file = o.Abrir(this);
        if (file != null) {
            String cad = file.getAbsolutePath();
            txtruta.setText(cad);
        }
    }//GEN-LAST:event_btnexaminarActionPerformed

    private void btnrestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurarActionPerformed
        if (txtruta.getText().length() > 0) {
            File file;
            file = new File(txtruta.getText());
            path = file.getAbsolutePath();
            int c = JOptionPane.showConfirmDialog(p, "Desea Restaurar esta Base de datos", "mensaje de confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (c == JOptionPane.YES_OPTION) {
                mysql=new MySQL();
                mysql.Comandos("drop database if exists rsystem;");
                mysql=new MySQL("localhost/mysql",user,password);
                mysql.Comandos("create database rsystem;");
                //mysql=new MySQL();
                backup = "cmd.exe /k start C:\\Users\\USER\\Desktop\\restore.bat";
               // C:\Users\USER\Desktop
                //backup = "cmd.exe /k start d:\\Users\\IVAN\\Desktop\\restore.bat c/ mysql --user=" + user + " --password=" + password + " " + bd + " < " + path;

//backup = " --user=" + user + " --password=" + password + " " + bd + " < " + path;
                System.out.println(backup);
                //try {
//                    Process child = Runtime.getRuntime().exec("cmd c/ C:\\Program Files\\MySQL\\MySQL Server 5.6\\bin\\mysql.exe --user=root --password=12345 tareaprogramacion < d:\\Users\\IVAN\\Desktop\\tareaprogramacion.sql");
                    //Process child=Runtime.getRuntime().exec("d:\\Users\\IVAN\\Desktop\\restore.bat");
                    Runtime aplicacion = Runtime.getRuntime(); 
        try{aplicacion.exec("cmd.exe /K start C:\\Users\\USER\\Desktop\\restore.bat");
                    //InputStream inputstream = child.getInputStream();
//BufferedInputStream bufferedinputstream = new BufferedInputStream(inputstream);
//System.out.println(bufferedinputstream);
                } catch (IOException ex) {
                    Logger.getLogger(RestaurarBD.class.getName()).log(Level.SEVERE, null, ex);
                }
                //mysql.Comandos(backup);
                JOptionPane.showMessageDialog(p, "La Base de Datos ha sido Restaurada Correctamente");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnrestaurarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        restaurar("12345","root","gourtmet");
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexaminar;
    private javax.swing.JButton btnrestaurar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}